app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('harshini/',harshini,name='harshini'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('kavya/',kavya,name='kavya'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here


def harshini(request):
    return render(request,'harshini.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def kavya(request):
    return render(request,'kavya.html')
 

templates/harshini.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>harshini harini geetha rishitha anusha</h1>
        <h2>we are friends</h2>

        <a href="{% url 'app2:kavya' %}"<h1>our gang</h1></a>

    </center>
</body>
</html>

templates/kavya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>in our group geetha and harini both are rowdys</h1>
    <h1>rishi and anusha is very silent</h1>
    <h1>nice friends</h1>
    <a href="{% url 'app1:harshini' %}"><h1> go back to beautiful gang</h1></a>
    </center>
</body>
</html>